services:
  reverse_proxy:
    image: nginx:latest
    container_name: el_nginx
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./Frontend:/usr/share/nginx/html

    networks:
      - red_publica
      - red_privada
  
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: api_flask

    networks:
      - red_privada

networks:
  red_publica:
    driver: bridge
  red_privada:
    driver: bridge